"""Tests for the alternate-source instrument.

Every assertion here is about **arithmetic or refusal**.  None is about the quality of
the alternate source in the paired fixture, because that fixture was generated by
``scripts/make_fixtures.py`` and any assertion about its alternate's accuracy would be an
assertion about a random number generator dressed as a finding.

The distinction is worth stating precisely, because it is easy to write the wrong test
here and it would look right:

* ``the recovery rate is 6/11`` -- fine.  It is a statement about the counting.
* ``the recovery rate is above 0.5`` -- not fine.  It is a statement about the generator
  that would read, to anyone scanning the suite, as support for the routing hypothesis.
"""

from __future__ import annotations

from dataclasses import replace
from datetime import date
from pathlib import Path

import pytest

from assurance_planner.artifacts import (
    ArtifactIdentityError,
    SyntheticArtifactError,
    artifact_document,
    qualification_from_document,
)
from assurance_planner.characterization import CaseRun, CharacterizationRun, characterize
from assurance_planner.complementarity import (
    POINT_ESTIMATE_FLOOR,
    Sufficiency,
    analyse_complementarity,
    errors_to_decide,
    paired_errors,
    required_paired_cases,
)
from assurance_planner.complementarity_report import UNMEASURED, render_complementarity
from assurance_planner.domain import FailureModeRef, QualificationKey, SourceVersionRef
from assurance_planner.loader import load_characterization

DATA = Path(__file__).resolve().parents[1] / "data"
PAIRED = DATA / "SYNTHETIC_paired_runs.yaml"


@pytest.fixture
def paired() -> CharacterizationRun:
    return load_characterization(PAIRED)


@pytest.fixture
def mixed() -> CharacterizationRun:
    """A pre-existing primary-only run, used to check what absence renders as."""
    return load_characterization(DATA / "judge_runs_mixed.yaml")


def _case(
    case_id: str,
    reference: bool,
    primary: str,
    alternate: str = "",
    slice_id: str = "s",
) -> CaseRun:
    return CaseRun(
        case_id=case_id,
        reference_label=reference,
        outcomes=tuple(c == "1" for c in primary),
        alternate_outcomes=tuple(c == "1" for c in alternate),
        slice_id=slice_id,
    )


def _run(cases: tuple[CaseRun, ...], alternate: bool = True) -> CharacterizationRun:
    return CharacterizationRun(
        evaluator_version=SourceVersionRef("primary", "v1"),
        failure_mode=FailureModeRef("MODE", "v1"),
        population_id="pop",
        distribution_id="dist",
        cases=cases,
        alternate_version=SourceVersionRef("alt", "v1") if alternate else None,
    )


# --------------------------------------------------------------------------------
# The 2x2 itself
# --------------------------------------------------------------------------------


def test_the_four_cells_count_what_their_names_say():
    """One case per cell, hand-checkable.

    ``111`` is a unanimous flag and ``000`` a unanimous pass, so on a
    reference-positive case ``111`` is correct and ``000`` is wrong. Four cases, four
    cells, and the order of the arguments is the thing most likely to be wrong.
    """
    table = paired_errors(
        (
            _case("both-right", True, "111", "111"),
            _case("primary-wrong", True, "000", "111"),
            _case("alternate-wrong", True, "111", "000"),
            _case("both-wrong", True, "000", "000"),
        )
    )
    assert table.neither_wrong == 1
    assert table.primary_only_wrong == 1
    assert table.alternate_only_wrong == 1
    assert table.both_wrong == 1
    assert table.decided == 4
    assert table.primary_errors == 2
    assert table.alternate_errors == 2


def test_an_unpaired_case_is_excluded_rather_than_counted_as_agreement():
    """The failure mode this guards is the quiet one.

    A case never sent to the alternate has no alternate verdict. Treating its absence
    as agreement would inflate ``neither_wrong`` on exactly the cases nobody looked at,
    which makes a partially-collected study look like a complete one.
    """
    table = paired_errors(
        (_case("paired", True, "111", "111"), _case("lonely", True, "000"))
    )
    assert table.unpaired == 1
    assert table.decided == 1
    assert table.neither_wrong == 1
    assert table.both_wrong == 0


def test_a_tie_on_either_side_removes_the_case_from_the_table():
    """A tie is not an answer, and resolving it here would invent an observation.

    Both directions are checked, because the asymmetric bug -- resolving the primary's
    ties but not the alternate's -- would silently make the primary look decisive.
    """
    primary_tie = paired_errors((_case("a", True, "10", "111"),))
    alternate_tie = paired_errors((_case("b", True, "111", "10"),))
    assert primary_tie.undecided == 1 and primary_tie.decided == 0
    assert alternate_tie.undecided == 1 and alternate_tie.decided == 0


def test_disagreement_equals_the_two_off_diagonal_cells():
    """An internal consistency identity, and it is not a tautology in the code.

    With binary verdicts and a shared reference label, the sources agree whenever they
    are both right and whenever they are both wrong, and disagree exactly when one is
    right. ``verdict_disagreements`` is counted from the verdicts and the off-diagonal
    cells are counted from correctness, by separate branches; if they ever disagree,
    one of the two is being computed against the wrong thing.
    """
    table = paired_errors(
        (
            _case("a", True, "111", "111"),
            _case("b", True, "000", "111"),
            _case("c", False, "111", "000"),
            _case("d", True, "000", "000"),
            _case("e", False, "000", "000"),
        )
    )
    assert table.verdict_disagreements == (
        table.primary_only_wrong + table.alternate_only_wrong
    )


# --------------------------------------------------------------------------------
# The statistics read off it
# --------------------------------------------------------------------------------


def test_the_recovery_rate_and_the_shared_error_fraction_are_one_number():
    """They sum to 1 on the same denominator, and the report says so.

    Kept as a test because the two get quoted side by side as though they were
    independent evidence, and a reader who believes that will double-count.
    """
    table = paired_errors(
        (
            _case("a", True, "000", "111"),
            _case("b", True, "000", "111"),
            _case("c", True, "000", "000"),
        )
    )
    recovery = table.alternate_correct_given_primary_wrong
    shared = table.primary_errors_shared
    assert recovery.trials == shared.trials == 3
    assert recovery.point + shared.point == pytest.approx(1.0)


def test_phi_is_none_when_a_margin_is_empty_rather_than_zero():
    """Undefined association must not print as reassuring independence.

    With no alternate errors at all the 2x2 has an empty column and phi has a zero
    denominator. Returning 0.0 there would read as "the errors are unassociated", which
    is the most favourable possible interpretation of no data.
    """
    no_alternate_errors = paired_errors(
        (_case("a", True, "000", "111"), _case("b", True, "111", "111"))
    )
    assert no_alternate_errors.alternate_errors == 0
    assert no_alternate_errors.error_association_phi is None

    both_margins = paired_errors(
        (
            _case("a", True, "000", "000"),
            _case("b", True, "111", "111"),
            _case("c", True, "000", "111"),
            _case("d", True, "111", "000"),
        )
    )
    assert both_margins.error_association_phi == pytest.approx(0.0)


def test_perfectly_coincident_errors_give_phi_of_one():
    """The result that would kill the routing hypothesis, computed correctly.

    If the alternate is wrong exactly where the primary is wrong, no routing policy
    helps at any budget. phi = +1 is what that looks like, and the instrument has to be
    able to produce it -- an instrument that can only produce favourable numbers is not
    measuring anything.
    """
    table = paired_errors(
        (
            _case("a", True, "000", "000"),
            _case("b", True, "000", "000"),
            _case("c", True, "111", "111"),
            _case("d", True, "111", "111"),
        )
    )
    assert table.error_association_phi == pytest.approx(1.0)
    assert table.alternate_correct_given_primary_wrong.point == 0.0
    assert table.joint_error_rate.point == 0.5


def test_the_error_floor_is_about_presentation_and_not_about_sufficiency():
    """16 is retained only as a "quote the interval" warning, and carries no verdict.

    The distinction is the whole point of the corpus red-team's fourth retraction. A
    thin denominator says the point estimate is a bad summary of the interval; it says
    nothing about whether the interval answers a question, because that depends on a
    threshold the denominator knows nothing about. Both halves are asserted: a
    12-error sample is thin *and* decisive against a distant threshold, and a
    20-error sample is not thin *and* inconclusive against a near one.
    """
    assert POINT_ESTIMATE_FLOOR == 16
    thin = paired_errors(
        tuple(_case(f"w{i}", True, "000", "111" if i < 9 else "000") for i in range(12))
    ).alternate_correct_given_primary_wrong
    assert thin.trials == 12 and thin.thin_denominator
    #: Thin, and still decisive: 0.75 on 12 errors spans [0.468, 0.911], which clears
    #: a break-even of 0.20 outright.
    assert thin.against(0.20) is Sufficiency.ABOVE

    fat = paired_errors(
        tuple(_case(f"w{i}", True, "000", "111" if i < 15 else "000") for i in range(20))
    ).alternate_correct_given_primary_wrong
    assert fat.trials == 20 and not fat.thin_denominator
    #: Not thin, and still undecided, because 0.70 is inside the interval.
    assert fat.against(0.70) is Sufficiency.INCONCLUSIVE


def test_an_undeclared_break_even_is_refused_rather_than_defaulted():
    """No threshold means no question, and no question cannot be answered by data.

    The failure this guards is the one the module used to commit: substituting 0.5 for
    a threshold nobody declared, then reporting the comparison in the register of a
    measurement. ``UNDECLARED`` has to be distinguishable from ``INCONCLUSIVE`` -- the
    first is a missing input, the second is a finding.
    """
    table = paired_errors(
        tuple(_case(f"w{i}", True, "000", "111" if i < 9 else "000") for i in range(12))
    )
    conditional = table.alternate_correct_given_primary_wrong
    assert conditional.against(None) is Sufficiency.UNDECLARED
    assert not Sufficiency.UNDECLARED.decisive
    assert not Sufficiency.INCONCLUSIVE.decisive

    #: An empty denominator is NO_DATA even when a threshold *is* declared: the reason
    #: nothing can be concluded is the absence of observations, not of policy.
    assert paired_errors(()).alternate_correct_given_primary_wrong.against(
        0.5
    ) is Sufficiency.NO_DATA


def test_an_analysis_without_a_declared_break_even_is_never_decisive():
    run = _run(tuple(_case(f"w{i}", True, "000", "111") for i in range(40)))
    assert analyse_complementarity(run).recovery_sufficiency is Sufficiency.UNDECLARED
    assert not analyse_complementarity(run).decisive
    assert analyse_complementarity(run, 0.5).decisive

    with pytest.raises(ValueError, match="not a probability"):
        analyse_complementarity(run, 1.5)


def test_the_sample_size_is_set_by_the_gap_to_the_threshold_not_by_a_constant():
    """The arithmetic that falsified the 16-error rule, asserted so it stays falsified.

    The same observed recovery of 0.60 needs 3 errors to clear a break-even of 0.10 and
    91 to clear one of 0.50 -- a thirtyfold swing driven entirely by an economic input.
    No fixed denominator can stand in for that, which is why sufficiency takes a
    threshold and the floor above does not.
    """
    assert errors_to_decide(0.60, 0.10) == 3
    assert errors_to_decide(0.60, 0.50) == 91
    assert errors_to_decide(0.75, 0.70) == 306
    #: An interval cannot exclude the point it is centred on, at any sample size. The
    #: honest answer is "no such study", not a large number.
    assert errors_to_decide(0.50, 0.50) is None


def test_required_paired_cases_scales_with_the_primary_being_accurate():
    """Under *representative* sampling, an accurate primary makes errors expensive.

    Errors are the denominator of the conditional, so a primary wrong once in twenty
    buys 16 of them only at 320 paired cases. The qualifier matters: this is a property
    of representative sampling, not of complementarity, and the errors figure is now a
    caller's argument rather than a constant this module believes in.
    """
    assert required_paired_cases(1.0, 16) == 16
    assert required_paired_cases(0.20, 16) == 80
    assert required_paired_cases(0.05, 16) == 320
    #: Not zero.  A primary with no errors has no routing question, which is a different
    #: statement from "no cases are needed".
    assert required_paired_cases(0.0, 16) is None


# --------------------------------------------------------------------------------
# Schema and identity
# --------------------------------------------------------------------------------


def test_alternate_observations_without_a_named_source_are_refused():
    """An unattributed observation cannot be keyed to a qualification slot.

    The whole qualification key exists to stop a measurement of one source being read
    as a measurement of another. A paired file that records a second source's verdicts
    without saying which source they came from reintroduces that hole at ingest.
    """
    with pytest.raises(ValueError, match="alternate source version"):
        _run((_case("a", True, "111", "111"),), alternate=False)


def test_the_run_id_changes_when_only_the_alternate_verdicts_change():
    """Two studies differing only in the alternate's verdicts are different studies.

    If the content digest ignored the alternate column, an artifact regenerated after
    re-running the alternate would keep the old id and the two would be indistinguishable
    -- which is the exact question the digest was added to answer.
    """
    first = _run((_case("a", True, "111", "111"),))
    second = _run((_case("a", True, "111", "000"),))
    assert first.run_id != second.run_id


def test_the_alternate_view_is_the_alternate_and_covers_paired_cases_only():
    """``alternate_view`` swaps the columns; it does not reinterpret them.

    Restricting to paired cases is load-bearing: an alternate sensitivity computed over
    a different case set than the primary's cannot be differenced against it, and the
    difference is the first thing anyone will compute.
    """
    run = _run(
        (
            _case("paired", True, "111", "000"),
            _case("unpaired", True, "111"),
        )
    )
    view = run.alternate_view()
    assert view.evaluator_version == SourceVersionRef("alt", "v1")
    assert view.alternate_version is None
    assert [c.case_id for c in view.cases] == ["paired"]
    assert view.cases[0].outcomes == (False, False, False)
    assert not view.cases[0].has_alternate
    #: Identity other than the source version is preserved: the alternate was measured
    #: on the same population against the same system.
    assert view.failure_mode == run.failure_mode
    assert view.population_id == run.population_id
    assert view.distribution_id == run.distribution_id


def test_an_alternate_artifact_keyed_to_the_alternate_refuses_the_primary_slot():
    """Fail-closed identity, inherited rather than reimplemented.

    The alternate's artifact goes through exactly the machinery the primary's does, so
    it gets the same refusal for free. Asserted here because "for free" is a claim about
    code that could stop being true.
    """
    run = replace(
        _run(
            tuple(
                _case(f"c{i}", i % 2 == 0, "111" if i % 2 == 0 else "000", "110")
                for i in range(10)
            )
        ),
        measured_on=date(2026, 9, 26),
    )
    document = artifact_document(characterize(run.alternate_view(), 0.05))
    assert document["identity"]["evaluator"] == "alt@v1"

    with pytest.raises(ArtifactIdentityError, match="source_version"):
        qualification_from_document(
            document,
            expected_key=QualificationKey(
                source_version=SourceVersionRef("primary", "v1"),
                failure_mode=FailureModeRef("MODE", "v1"),
                population_id="pop",
                distribution_id="dist",
            ),
        )


# --------------------------------------------------------------------------------
# Synthetic input cannot become evidence
# --------------------------------------------------------------------------------


def test_the_paired_fixture_declares_itself_synthetic(paired):
    """The marker is structural, not prose.

    A ``limitations`` string is a footnote and footnotes get dropped when a table is
    pasted somewhere else. ``synthetic: true`` is a field that code branches on.
    """
    assert paired.synthetic is True
    assert PAIRED.name.startswith("SYNTHETIC_")
    assert "SYNTHETIC" in str(paired.alternate_version)
    assert any("SYNTHETIC" in limit for limit in paired.limitations)


def test_an_artifact_from_synthetic_observations_can_be_written_but_never_loaded(paired):
    """The loop that makes the synthetic fixture safe to keep in the repository.

    It has to be writable, because writing it is how the artifact machinery gets
    exercised on paired data. It must not be loadable, because a qualification artifact
    is a planner input and there is nothing behind this one.
    """
    document = artifact_document(characterize(paired.alternate_view(), 0.05))
    assert document["synthetic"] is True
    assert list(document)[:2] == ["schema", "synthetic"]

    with pytest.raises(SyntheticArtifactError):
        qualification_from_document(document)


def test_the_report_announces_synthetic_input_and_names_no_recommendation(paired):
    """Two properties of the report, and the second is the one under instruction.

    The banner is at the top. And every decision cell reads UNMEASURED -- there is no
    code path in the report module that writes anything else into one, so this holds for
    real data too until an artifact backs it.
    """
    analysis = analyse_complementarity(paired)
    text = render_complementarity(
        analysis,
        characterize(paired, 0.05),
        characterize(paired.alternate_view(), 0.05),
    )
    assert "SYNTHETIC DATA" in text.splitlines()[1]
    assert not analysis.measured

    for decision in (
        "Replace the primary",
        "Keep both, route selectively",
        "Reject the alternate",
    ):
        line = next(l for l in text.splitlines() if l.strip().startswith(decision))
        assert UNMEASURED in line, f"'{decision}' was given a verdict"

    #: No recommendation vocabulary anywhere in the document.
    lowered = text.lower()
    for word in ("recommend", "we should", "conclude that", "best option"):
        assert word not in lowered


def test_on_an_all_failures_corpus_disagreement_and_recovery_are_one_number():
    """The arithmetic behind the warning the statistics block prints unconditionally.

    Every case here has the primary wrong, which is what a failure-enriched corpus is.
    With binary verdicts against a shared reference the sources then disagree exactly
    when the alternate is right, so two statistics printed four lines apart under
    different names are the same quantity -- and the production disagreement rate,
    which this would be read as, is smaller by a factor of the primary error rate.

    Phi is already refused on this table, but by the empty-margin rule rather than by
    any understanding of the sampling: the primary-correct row is empty. That rule does
    not fire on a *partially* enriched corpus, where phi is a plausible number computed
    from reweighted cells. Nothing in the schema records the sampling design and no
    arithmetic recovers it, which is why the warning is prose and not a check.
    """
    table = paired_errors(
        tuple(_case(f"f{i}", True, "000", "111" if i < 7 else "000") for i in range(10))
    )
    assert table.primary_errors == table.decided == 10
    assert table.disagreement_rate.point == table.alternate_correct_given_primary_wrong.point
    assert table.error_association_phi is None


def test_the_report_warns_that_phi_and_disagreement_assume_representative_sampling(
    paired,
):
    text = render_complementarity(
        analyse_complementarity(paired),
        characterize(paired, 0.05),
        characterize(paired.alternate_view(), 0.05),
    )
    statistics = text.split("Complementarity statistics")[1].split("Is the recovery")[0]
    assert "Phi is not invariant to" in statistics
    assert "the same number under two names" in statistics


def test_the_report_separates_the_observation_the_interval_and_the_declared_threshold(
    paired,
):
    """Four lines, because they are four different kinds of thing.

    Collapsing them is exactly how an economic constant came to be printed in the
    register of a statistical convention. The first two are measurements, the third is
    a policy input and is labelled as one, and only the fourth is a claim -- a claim
    relative to the third rather than an absolute.
    """
    text = render_complementarity(
        analyse_complementarity(paired, 0.20),
        characterize(paired, 0.05),
        characterize(paired.alternate_view(), 0.05),
    )
    section = text.split("Is the recovery evidence sufficient")[1].split("Per slice")[0]
    assert "observed recovery" in section
    assert "statistical uncertainty" in section
    assert "declared break-even r*" in section
    assert "POLICY INPUT, not measured here" in section
    assert "decision support" in section

    #: The retraction is printed, not merely enacted: 0.5 appears only as the rule that
    #: was withdrawn, never as a comparison being made.
    assert "0.5 was an undeclared economic" in section


def test_without_a_declared_break_even_the_report_refuses_to_call_anything_sufficient(
    paired,
):
    """Descriptive statistics remain; the verdict does not.

    A study that was never told what would count as success has not failed to measure
    anything -- it has been asked no question. The report has to render that as a
    missing input rather than as a weak result or, worse, as a passing one.
    """
    analysis = analyse_complementarity(paired)
    text = render_complementarity(
        analysis, characterize(paired, 0.05), characterize(paired.alternate_view(), 0.05)
    )
    assert analysis.recovery_sufficiency is Sufficiency.UNDECLARED
    assert "UNDECLARED  (none supplied; this is an input, not a measurement)" in text
    assert "NOT DECISION-SUFFICIENT" in text
    #: Still reports the observation and its uncertainty.
    assert "0.545" in text and "[0.280, 0.787]" in text


def test_a_single_source_run_reports_unmeasured_rather_than_zero_complementarity(mixed):
    """Absence of data is not a low reading, and the report must not render it as one.

    ``data/judge_runs_mixed.yaml`` has no alternate column at all. A recovery rate of
    0.000 printed against it would be false in the direction that kills a hypothesis
    for the wrong reason.
    """
    analysis = analyse_complementarity(mixed)
    assert not analysis.has_paired_data
    text = render_complementarity(analysis, characterize(mixed, 0.05), None)
    assert "No paired observations." in text
    assert "Complementarity is not low here" in text
    assert UNMEASURED in text


# --------------------------------------------------------------------------------
# Cost and latency
# --------------------------------------------------------------------------------


def test_missing_cost_and_latency_are_reported_unknown_not_filled_in(paired):
    """The short-form fixture records no per-observation economics, and says so.

    ``CostModel`` carries a placeholder price for the alternate. Reading it here would
    produce a cost comparison that looks measured, which is worse than an empty cell
    because an empty cell prompts someone to go and collect the data.
    """
    text = render_complementarity(
        analyse_complementarity(paired),
        characterize(paired, 0.05),
        characterize(paired.alternate_view(), 0.05),
    )
    economics = text.split("Cost and latency")[1].split("Alternate stochasticity")[0]
    assert economics.count(UNMEASURED) == 4
    assert "0.75" not in economics


def test_recorded_cost_and_latency_are_used_when_the_harness_supplies_them(tmp_path):
    """The long form is the shape a real harness emits, and both sides are parsed.

    Checked on the alternate side specifically: the primary's annotation has been
    parsed since the previous pass, and an alternate column that silently dropped its
    cost annotation would leave the economics half-measured without failing anything.
    """
    document = tmp_path / "paired.yaml"
    document.write_text(
        """
experiment:
  evaluator_version: judge@v4
  alternate_version: reviewer@v1
  failure_mode_version: MODE@v1
  population_id: pop
  sut_distribution_id: dist
cases:
  - case_id: C-001
    reference_label: fail
    observations:
      - {verdict: fail, latency_ms: 2000, cost: 0.0625}
    alternate_observations:
      - {verdict: pass, latency_ms: 240000, cost: 0.75}
""",
        encoding="utf-8",
    )
    run = load_characterization(document)
    case = run.cases[0]
    assert case.costs_usd == (0.0625,)
    assert case.alternate_costs_usd == (0.75,)
    assert case.alternate_latencies_ms == (240000.0,)
    assert case.alternate_majority_verdict is False


def test_partial_cost_annotation_on_the_alternate_is_refused(tmp_path):
    """The same all-or-none rule the primary has, because a mean over half the
    observations is not a mean over the observations."""
    document = tmp_path / "partial.yaml"
    document.write_text(
        """
experiment:
  evaluator_version: judge@v4
  alternate_version: reviewer@v1
  failure_mode_version: MODE@v1
  population_id: pop
  sut_distribution_id: dist
cases:
  - case_id: C-001
    reference_label: fail
    observations: [{verdict: fail}]
    alternate_observations:
      - {verdict: pass, cost: 0.75}
      - {verdict: pass}
""",
        encoding="utf-8",
    )
    with pytest.raises(ValueError, match="alternate_observations"):
        load_characterization(document)
